### ISSUE TITLE
Error parsing db.json, container don't work

### ISSUE THREAD

**Issue by AlexxNB** [nosinovacao/docker-timeoff-management#2]
Hello!

Can't run the container: 
```
SyntaxError: /app/timeoff-management/config/db.json: Unexpected token : in JSON at position 15
```

**Comment by APMarte** [comment]
Hello @AlexxNB, 

Thanks for your input. 
Did you run docker image with env variables?  

I think your docker-entrypoint.sh have an error that only manifests itself when you run the image without db.json configuration variables (MYSQL_USER,MYSQL_HOST,MYSQL_PASSWORD,MYSQL_DATABASE)
